package com.ccea.web.action;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.webflow.execution.Event;
import org.springframework.webflow.execution.RequestContext;

import com.ccea.persistence.exceptions.DataStoreException;
import com.ccea.persistence.model.pojo.User;
import com.ccea.persistence.report.UIDataManager;

public class UserLoginAction extends CeaAbstractEventAction {
	
	protected static Logger logger = LoggerFactory
            .getLogger(UserLoginAction.class);
	
	@Autowired
	UIDataManager uiDataManager;
	
	public UserLoginAction() {
		super();
	}

	
	public Event checkUserLogin(RequestContext requestContext) throws Exception {
		logger.info("enter UserLoggerAction");
		User user = (User)requestContext.getFlowScope().get("userBean");
		try {
				if(uiDataManager.checkLoginDetails(user.getLogin(), user.getPassword())) {
					logger.info("exit succcess UserLoggerAction");
					return success;
				}
		} catch (DataStoreException e) {
			requestContext.getFlowScope().put("userLoginMessage", "Error occurred while validating user login, check dat and try again or see administrator.");
		}
		logger.info("exit error UserLoggerAction");
		return error;
	}

}
