package com.ccea.web.action;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.webflow.action.MultiAction;
import org.springframework.webflow.execution.Action;
import org.springframework.webflow.execution.Event;
import org.springframework.webflow.execution.RequestContext;

import com.ccea.persistence.exceptions.DataStoreException;
import com.ccea.persistence.model.pojo.Project;
import com.ccea.persistence.report.UIDataManager;

public class EnterProjectAction extends MultiAction {

	@Autowired
	UIDataManager uiDataManager;
	
	public EnterProjectAction() {
		 super();
	}

	 
	
	
	public Event storeProjectBean(RequestContext context) throws Exception {
				
        Project p = (Project)context.getFlowScope().get("projectBean");
		try {
           uiDataManager.addProject(p);
		} catch (DataStoreException e) {
			context.getFlowScope().put("newProjectMesage","Error occurred during save operation, "
					+ "check data and try again or see system administrator. ");
			return new Event(this,"error");
		}
	    return new Event(this,"success");
	}
	
	public Event getProjectBean(RequestContext context) throws Exception {
		
		Project project = new Project();
		
        context.getFlowScope().put("projectBean", project);
		
	    return new Event(this,"success");
	}
	
	public Event getAllProjectBean(RequestContext context) throws Exception {
		
		ProjectBeanWrapper projects = new ProjectBeanWrapper();
		
        context.getFlowScope().put("projectBean", project);
		
	    return new Event(this,"success");
	}

}
